### ISSUE TITLE
Difficult to test release candidates

### ISSUE THREAD

**Issue by snovotill** [OpenPrinting/libcups#96]
**Describe the bug**
The readme.md file does not give any instructions for testing libcups 3 release candidates on end-user systems. This prevents most people from testing it and providing feedback.

**To Reproduce**
I tried to google, I've asked Gemeni, Copilot and ChatGPT, but have not had any success in tracking down a branch of CUPS 3 on GitHub, which is compatible with libcups 3 release candidate. Some guidance on how to actually test-drive libcups 3 release candidate would be very helpful to those of us not in the "inner circle" of developers.

**Expected behavior**
Be able to follow either specific instructions or a general overview on how to *actually* test-drive libcups 3 release candidate on popular distros such as Debian testing etc.

**Screenshots**
None.

**System Information:**
 - OS: [e.g. Debian Trixie
 - Version: libcups 3 rc3

**Additional context**
None

**Comment by michaelrsweet** [comment]
The [cups](https://github.com/OpenPrinting/cups) repository is for CUPS 2.x development and the old PPD-based driver model.

*This* repository provides the basis for what is collectively called "CUPS 3.0". What you can test here is the CUPS library itself linked against various programs and the "ippeveprinter", "ippfind", "ipptool", and "ipptransform" tools that are bundled with the library. In the (hopefully) near future, the [cups-local](https://github.com/OpenPrinting/cups-local) repository will have testable releases against libcups, but even then you will need to re-build other OpenPrinting components for your system to use it since the level of integration on Linux distros is so deep...

@tillkamppeter may be able to provide more details for testing on Ubuntu/Debian - let's just say "it's complicated"...
